spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        username: admin
        password: admin
        url: jdbc:postgresql://localhost:5432/reservation_system
        type: org.postgresql.ds.PGSimpleDataSource
    security:
        user:
            name: user
            password: user
